version: '3.7'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: payment_pass
      POSTGRES_USER: payment_user
      POSTGRES_DB: payment
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U payment_user -d payment"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend API
  api:
    build: .
    ports:
      - '8000:8000'
    environment:
      - DATABASE_URL=postgresql://payment_user:payment_pass@db:5432/payment
      - NODE_ENV=development
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
